const seeds={"East Lyme":82,Killingly:78,Lebanon:76,Plainfield:74,Voluntown:72,Sterling:70,Canterbury:69,Scotland:68,Hampton:66,Brooklyn:64,Groton:61,Middletown:58};let features=[],selected=null,geoLayer,labelLayer,scoreShift=0;
const map=L.map('map',{zoomControl:true,attributionControl:true}).setView([41.55,-72.68],8);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',maxZoom:18}).addTo(map);labelLayer=L.layerGroup().addTo(map);
const hash=s=>[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7);const base=n=>seeds[n]??(42+hash(n)%39);const score=n=>Math.max(10,Math.min(96,base(n)+scoreShift));const color=s=>s>=81?'#16b978':s>=61?'#70d35d':s>=41?'#ecd84f':s>=21?'#ef8541':'#d83247';
const metrics=n=>{let h=hash(n);return {"Land availability":45+h%48,"Land cost":40+(h>>3)%51,"Environmental fit":42+(h>>6)%48,"Infrastructure":40+(h>>9)%52,"Accessibility":38+(h>>12)%55,"Tax environment":40+(h>>15)%49,"Growth outlook":38+(h>>18)%54}};
function townName(f){return (f.properties.BASENAME||f.properties.NAME||'Municipality').replace(/ town$/i,'')}
function style(f){const s=score(townName(f));return {color:'#e8f1f5',weight:selected===f?3:1,fillColor:color(s),fillOpacity:.78}}
function draw(){if(geoLayer)geoLayer.remove();labelLayer.clearLayers();geoLayer=L.geoJSON({type:'FeatureCollection',features},{style,onEachFeature:(f,l)=>{const n=townName(f);l.bindTooltip(`${n} · ${score(n)}/100`,{sticky:true});l.on('click',()=>select(f));if(document.getElementById('labels').checked){const c=l.getBounds().getCenter();L.marker(c,{interactive:false,icon:L.divIcon({className:'town-label',html:n,iconSize:[90,16],iconAnchor:[45,8]})}).addTo(labelLayer)}}}).addTo(map);map.fitBounds(geoLayer.getBounds(),{padding:[15,15]});renderLists()}
async function loadMap(){const u='https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/1/query?where=STATE%3D%2709%27&outFields=BASENAME%2CNAME%2CGEOID&returnGeometry=true&outSR=4326&f=geojson';try{const r=await fetch(u);if(!r.ok)throw Error();const g=await r.json();features=g.features.sort((a,b)=>townName(a).localeCompare(townName(b)));draw();document.getElementById('loading').remove()}catch(e){document.getElementById('loading').textContent='Municipal boundary service is temporarily unavailable. Refresh to try again.'}}
function select(f){selected=f;const n=townName(f),s=score(n),m=metrics(n);document.getElementById('townName').textContent=n;document.getElementById('townSub').textContent='Connecticut municipality · Census GEOID '+(f.properties.GEOID||'—');document.getElementById('score').textContent=s;document.getElementById('summary').textContent=`${n} is ranked as a preliminary screening candidate under the current preferences. The score is a prototype planning signal—not a determination that any parcel is buildable.`;document.getElementById('metrics').innerHTML=Object.entries(m).map(([k,v])=>`<div class="metric"><span>${k}</span><div class="bar"><i style="width:${v}%;background:${color(v)}"></i></div><b>${v}</b></div>`).join('');document.getElementById('facts').innerHTML=`<div><small>Current rank</small><b>#${ranked().findIndex(x=>townName(x)===n)+1}</b></div><div><small>Geometry</small><b>Official boundary</b></div><div><small>Score status</small><b>Prototype</b></div><div><small>Next step</small><b>Parcel research</b></div>`;document.querySelectorAll('#parcels,#profile').forEach(x=>x.disabled=false);draw()}
function ranked(filter=''){return features.filter(f=>townName(f).toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>score(townName(b))-score(townName(a)))}
function rows(list){return `<div class="rank head"><span>#</span><span>Municipality</span><span>Score</span><span>Relative result</span></div>`+list.map((f,i)=>{const n=townName(f),s=score(n);return `<div class="rank" data-town="${n}"><span>${i+1}</span><b>${n}</b><span>${s}</span><span class="bar"><i style="width:${s}%;background:${color(s)}"></i></span></div>`}).join('')}
function renderLists(){document.getElementById('topRankings').innerHTML=rows(ranked().slice(0,10));document.getElementById('fullRankings').innerHTML=rows(ranked(document.getElementById('search').value));document.querySelectorAll('.rank[data-town]').forEach(r=>r.onclick=()=>{const f=features.find(x=>townName(x)===r.dataset.town);showView('map');map.fitBounds(L.geoJSON(f).getBounds(),{maxZoom:11});select(f)});renderCompare()}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v+'View').classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelector('.table').style.display=v==='map'?'block':'none';if(v==='map')setTimeout(()=>map.invalidateSize(),20)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.getElementById('budget').oninput=e=>document.getElementById('budgetOut').textContent='$'+Math.round(e.target.value/1000)+'K';document.getElementById('analyze').onclick=()=>{scoreShift=(document.getElementById('budget').value-150000)/25000+(document.getElementById('availability').selectedIndex-1)*3-(document.getElementById('tax').selectedIndex-1)*2;draw()};document.getElementById('reset').onclick=()=>location.reload();document.getElementById('labels').onchange=e=>e.target.checked?draw():labelLayer.clearLayers();document.getElementById('boundaries').onchange=e=>{if(geoLayer)geoLayer.setStyle(f=>({...style(f),weight:e.target.checked?1:0}))};document.getElementById('search').oninput=renderLists;document.getElementById('quickSearch').oninput=e=>{showView('rankings');document.getElementById('search').value=e.target.value;renderLists()};document.getElementById('closeDetail').onclick=()=>{selected=null;document.getElementById('townName').textContent='Select a town';document.getElementById('score').textContent='—';draw()};
const modal=document.getElementById('modal');document.getElementById('closeModal').onclick=()=>modal.close();document.getElementById('parcels').onclick=()=>openModal('parcels');document.getElementById('profile').onclick=()=>openModal('profile');function openModal(type){const n=townName(selected);document.getElementById('modalBody').innerHTML=type==='parcels'?`<h2>${n}: Candidate Parcel Research</h2><p>This view is now functional as a research workflow. Parcel ranking will activate when parcel/CAMA and constraint layers are connected.</p><ol class="steps"><li>Filter parcels by minimum lot size and assessed land value.</li><li>Remove known flood, wetland, protected-land and steep-slope conflicts.</li><li>Check zoning, frontage, utilities and local regulations.</li><li>Rank surviving parcels and export a due-diligence shortlist.</li></ol><p><b>No candidate parcels are claimed yet.</b> This prevents prototype data from being mistaken for real due diligence.</p>`:`<h2>${n} Municipal Profile</h2><p><b>Prototype score:</b> ${score(n)}/100</p><p><b>Census GEOID:</b> ${selected.properties.GEOID||'—'}</p><p>This profile uses the municipality’s accurate Census boundary. Population, mill rate, zoning, housing values and development rules will appear here as verified sources are connected.</p><p><a href="https://www.google.com/search?q=${encodeURIComponent(n+' Connecticut zoning regulations')}" target="_blank">Research ${n} zoning ↗</a></p>`;modal.showModal()}
function renderCompare(){const options=ranked().map(f=>`<option>${townName(f)}</option>`).join('');document.getElementById('comparePickers').innerHTML=[0,1,2].map((_,i)=>`<select class="cmp"><option value="">Select town ${i+1}</option>${options}</select>`).join('');document.querySelectorAll('.cmp').forEach(x=>x.onchange=updateComparison)}function updateComparison(){const ns=[...document.querySelectorAll('.cmp')].map(x=>x.value).filter(Boolean);const keys=['Buildability score',...Object.keys(ns[0]?metrics(ns[0]):{})];document.getElementById('comparison').innerHTML=ns.length?`<div class="compareGrid"><b>Metric</b>${ns.map(n=>`<b>${n}</b>`).join('')}${keys.map(k=>`<span>${k}</span>${ns.map(n=>`<strong>${k==='Buildability score'?score(n):metrics(n)[k]}</strong>`).join('')}`).join('')}</div>`:''}
loadMap();
